image:
    name: swedishembedded/build:v0.24.5
    pull_policy: if-not-present

default:
  tags:
    - docker

stages:
 - check
 - build
 - test

# This job runs all code checks, unit and integration tests
check:
    stage: check
    artifacts:
        paths:
            - report.html
            - log.html
        expire_in: 1 week
        when: always
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    script:
        - ./scripts/init
        - ./scripts/check

# This job builds applications
build:
    stage: build
    dependencies:
        - check
    artifacts:
        paths:
            - build-doc/**/*.pdf
            - build-apps/**/zephyr.elf
            - build-release/**/release/
            - release/*
        expire_in: 1 week
        when: always
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    script:
        # for docs. Move to docker image.
        - apt-get update && apt-get install -qy tex-gyre
        - ./scripts/init
        - ./scripts/build-doc --sdk-only
        - ./scripts/build

# This job runs all system tests on built applications
test:
    stage: test
    dependencies:
        - build
    artifacts:
        paths:
            - build-tests/coverage*
        expire_in: 1 week
        when: always
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    script:
        - ./scripts/init
        - ./scripts/test

# This is a job that does the "long build"
# where we start with a fresh ubuntu image
build_from_scratch:
    image: ubuntu:latest
    stage: check
    rules:
        - if: $CI_PIPELINE_SOURCE == "web"
        - if: $CI_PIPELINE_SOURCE == "schedule"
    before_script:
        - bash -x ./scripts/install-sdk
        - bash -x ./scripts/init
    script:
        - bash -x ./scripts/check
        - bash -x ./scripts/build
        - bash -x ./scripts/test
