# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: sdk

  remotes:
    - name: swedishembedded
      url-base: https://github.com/swedishembedded
    - name: renode
      url-base: https://github.com/renode
    - name: imgui
      url-base: https://github.com/ocornut
    - name: epezent
      url-base: https://github.com/epezent/
  projects:
    - name: zephyr
      remote: swedishembedded
      revision: v3.0.0-swe
      import: true
    - name: renode
      path: renode
      revision: v1.13.1
      submodules: true
      remote: renode
    - name: control
      path: modules/lib/control
      revision: v0.34.0
      remote: swedishembedded
    - name: instruments
      path: tools/instruments
      revision: v0.34.0
      remote: swedishembedded
    - name: testing
      path: modules/test/testing
      revision: v0.34.0
      remote: swedishembedded
      import: true
    - name: imgui
      path: modules/lib/imgui
      revision: master
      remote: imgui
    - name: implot
      path: modules/lib/implot
      revision: master
      remote: epezent
