# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: sdk

  remotes:
    - name: swedishembedded
      url-base: https://github.com/swedishembedded
    - name: renode
      url-base: https://github.com/renode
  projects:
    - name: zephyr
      remote: swedishembedded
      revision: v3.0.0-swe
      import: true
    - name: renode
      path: renode
      revision: v1.13.1
      submodules: true
      remote: renode
    - name: control
      path: modules/lib/control
      revision: v0.35.1
      remote: swedishembedded
    - name: instruments
      path: tools/instruments
      revision: v0.35.1
      remote: swedishembedded
    - name: testing
      path: modules/test/testing
      revision: v0.34.0
      remote: swedishembedded
      import: true
