# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: sdk

  remotes:
    - name: swedishembedded
      url-base: https://github.com/swedishembedded
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
    - name: renode
      url-base: https://github.com/renode
    - name: imgui
      url-base: https://github.com/ocornut
    - name: epezent
      url-base: https://github.com/epezent/
  projects:
    - name: zephyr
      remote: swedishembedded
      revision: v3.0.0-swe
      import: true
    - name: cmock
      path: modules/test/cmock
      revision: f65066f15d8248e6dcb778efb8739904a4512087
      remote: throwtheswitch
    - name: unity
      path: modules/test/cmock/vendor/unity
      revision: 1958b977019c3ac19bb83350f7b26e60cbeb6c75
      remote: throwtheswitch
    - name: renode
      path: renode
      revision: v1.13.1
      submodules: true
      remote: renode
    - name: control
      path: modules/lib/control
      revision: main
      remote: swedishembedded
    - name: imgui
      path: modules/lib/imgui
      revision: master
      remote: imgui
    - name: implot
      path: modules/lib/implot
      revision: master
      remote: epezent
