#!/bin/bash

set -e

if [[ ! "$1" ]]; then
	echo "Usage: $0 <file>"
	exit 1
fi

# check that file is sorted
diff <(cat $1 | sort) <(cat $1) || {
    msg_err "File $1 is not sorted";
    echo "Run: sort -u -o $1 $1"
    exit 1
}

