#!/bin/bash

ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"

set -e

. ${ROOT}/../zephyr/zephyr-env.sh

$ROOT/../zephyr/scripts/twister \
	--integration \
	-c \
	-O build-all \
	-v \
	-i \
	-A boards \
	-T apps \
	-T tests \
	-T samples || {
	echo "Error while trying to build project"
	exit 1
}

make -C doc pdf || {
	echo "Error building documentation"
	exit 1
}
