#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Martin Schröder <info@swedishembedded.com>
# Consulting: https://swedishembedded.com/go
# Training: https://swedishembedded.com/tag/training

ROOT="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"

set -e

. ${ROOT}/VERSION
. ${ROOT}/../zephyr/zephyr-env.sh

BUILD_DIR=build-doc
SDK_ONLY=0

# Parse arguments (standard way of doing it in bash)
while [[ $# -gt 0 ]]; do
    case $1 in
	--sdk-only)
		SDK_ONLY=1
		shift
		;;
	esac
done

# Build documentation
(mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR} && cmake ../doc)
if [[ -z "$SDK_ONLY" ]]; then
	make -C ${BUILD_DIR} build-all pdf 2>&1 | tee ${BUILD_DIR}/build.log
else
	make -C ${BUILD_DIR} sdk-all sdk-pdf 2>&1 | tee ${BUILD_DIR}/build.log
fi

cat ${BUILD_DIR}/build.log | \
	grep -v "Not copying tabs assets" | \
	grep WARNING && {
	echo "ERROR: documentation has warnings!"
	# Disabling this for now since there are many zephyr warnings that need to be fixed
	#exit 1
}

[[ -f ${BUILD_DIR}/latex/sdk/swedishembedded.pdf ]] && {
	VERSION="$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH"
	DOC=$BUILD_DIR/latex/sdk/Swedish-Embedded-Platform-SDK-v$VERSION.pdf
	mv "$BUILD_DIR/latex/sdk/swedishembedded.pdf" "$DOC"
	echo "Documentation ready in $DOC"
}

