#!/bin/bash

ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"

set -e

. ${ROOT}/VERSION
. ${ROOT}/../zephyr/zephyr-env.sh

# Build applications and samples
$ROOT/../zephyr/scripts/twister \
	-p custom_board \
	-c \
	-O build-apps \
	-v \
	-i \
	-A boards \
	-T apps \
	-T samples || {
	echo "Error while trying to build project"
	exit 1
}

# Build documentation
make -C doc pdf || {
	echo "Error building documentation"
	exit 1
}

# Build releases
./scripts/release -b custom_board -s apps/shell
