#!/bin/bash

ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"

set -e

BUILD_DIR=$1

if [[ ! -d $BUILD_DIR ]]; then
	echo "Build directory $BUILD_DIR does not exist"
	echo "run ./scripts/build"
	exit 1
fi

# Filter coverage data
lcov \
	--extract $BUILD_DIR/coverage.info \
	"$PWD/drivers/*" \
	"$PWD/lib/*" \
	--rc lcov_branch_coverage=1 \
	-o $BUILD_DIR/coverage-project.info

# List all coverage data we have
lcov \
	--rc lcov_branch_coverage=1 \
	--list $BUILD_DIR/coverage-project.info

# Generate html report
genhtml $BUILD_DIR/coverage-project.info \
	--output-directory $BUILD_DIR/coverage-project \
	--rc lcov_branch_coverage=1

echo "HTML coverage report is in $BUILD_DIR/coverage-project"

# Check that we have full coverage
BRANCH_COVERAGE_TH=96
LINE_COVERAGE_TH=100

BRANCH_COVERAGE=$(\
	lcov \
	--rc lcov_branch_coverage=1 \
	--summary $BUILD_DIR/coverage-project.info | \
	grep "branches" | \
	sed -e 's/[[:space:]]*branches\.*: //g' | \
	sed -e 's/%.*//g' \
)
LINE_COVERAGE=$( \
	lcov \
	--rc lcov_branch_coverage=1 \
	--summary $BUILD_DIR/coverage-project.info | \
	grep "lines" | \
	sed -e 's/[[:space:]]*lines\.*: //g' | \
	sed -e 's/%.*//g' \
)

which bc || {
	echo "bc utility is not installed!"
	exit 1
}

if [[ $(echo "$BRANCH_COVERAGE_TH<=$BRANCH_COVERAGE" | bc) = "0" ]]; then
	echo "Error branch coverage - expected: $BRANCH_COVERAGE_TH, got: $BRANCH_COVERAGE)"
	exit 1
fi

if [[ $(echo "$LINE_COVERAGE_TH<=$LINE_COVERAGE" | bc) = "0" ]]; then
	echo "Error line coverage - expected: $LINE_COVERAGE_TH, got: $LINE_COVERAGE)"
	exit 1
fi

