#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

ROOT="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"
WORKSPACE="$(realpath "$ROOT/..")"

DOCKER_IMAGE="swedishembedded/build:v0.26.4-1"

HOST_UID=$(id -u)
HOST_GID=$(id -g)

PARAMETERS="$@"

docker run -it --rm \
        -v $WORKSPACE:$WORKSPACE \
        -v $HOME/.ssh/:/home/user/.ssh \
		$DOCKER_IMAGE /bin/bash -c \
        "cd $ROOT; sudo -u user $PARAMETERS"
