#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"
WORKSPACE="$(realpath $ROOT/..)"

DOCKER_IMAGE="swedishembedded/build:v0.24.5"

HOST_UID=$(id -u)
HOST_GID=$(id -g)

PARAMETERS="$@"

docker run -t --rm \
        -v $WORKSPACE:$WORKSPACE \
        -v $HOME/.ssh/:/home/user/.ssh \
		$DOCKER_IMAGE /bin/bash -c \
        "cd $ROOT; sudo -u user $PARAMETERS"
