#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Martin Schröder <info@swedishembedded.com>

ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"

# abort on error (note that this is only a fallback. You should still check
# return codes every single time!)
set -e

# Configure git hook
git config core.hooksPath .githooks

# Remove any existing west config (since we are reinitializing)
if [[ -d ../.west ]]; then
	rm -rf ../.west
fi

# Initialize the repository
west init -l .
west update

export ZEPHYR_TOOLCHAIN_VARIANT=zephyr

# Apply zephyr patches
$ROOT/scripts/apply-zephyr-patches || {
	echo "ERROR: Could not apply zephyr patches"
}

# Install python requirements
pip3 install -r ../zephyr/scripts/requirements.txt

# Install cmake tools for cmake-format
pip3 install cmakelang

# Install robot framework
pip3 install robotframework

. ../zephyr/zephyr-env.sh

west zephyr-export

