#!/bin/bash

# abort on error (note that this is only a fallback. You should still check
# return codes every single time!)
set -e

# Install apt packages (-qy means quet and say yes on all interactive questions)
sudo apt-get -qy update

# This is a workaround for tzdata installation (so it doesn't hang pipeline)
if [[ ! -z "${CI_JOB_TOKEN}" ]]; then
	TZ=America/Los_Angeles
	ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
	echo "$TZ" > /etc/timezone
fi

# Install zephyr dependencies (non-interactively)
DEBIAN_FRONTEND=noninteractive \
sudo apt install -qy --no-install-recommends \
	git gitlint cmake ninja-build gperf \
	ccache dfu-util device-tree-compiler wget \
	python3-dev python3-pip python3-setuptools \
	python3-tk python3-wheel xz-utils file \
	make gcc gcc-multilib g++-multilib libsdl2-dev > /dev/null

# Install zephyr sdk
wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.14.2/zephyr-sdk-0.14.2_linux-x86_64.tar.gz
wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.14.2/sha256.sum | shasum --check --ignore-missing
tar xf zephyr-sdk-0.14.2_linux-x86_64.tar.gz > /dev/null
rm zephyr-sdk-0.14.2_linux-x86_64.tar.gz
pushd zephyr-sdk-0.14.2
./setup.sh -t all -h
popd
rm -rf zephyr-sdk-0.14.2

# Install the west tool
pip3 install -U west
