name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
        image: docker.io/swedishembedded/build:v0.24.5
    steps:
    - name: Prepare
      run: |
          apt-get update
          apt-get install git-lfs
    - name: Configure git to trust the workspace despite the different owner
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          lfs: true
    - name: Build everything
      run: |
        ./scripts/init
        robot scrum
        # for some reason with github we must do this
        /opt/toolchains/zephyr-sdk-0.15.1/setup.sh -t all -h -c
        ./scripts/gen-tags cscope
        ./scripts/check
        ./scripts/build
        ./scripts/test
        robot post-build
