name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
        image: docker.io/swedishembedded/build:v0.24.6
    steps:
    - name: Prepare
      run: |
          apt-get update
          apt-get install -qy tex-gyre
    - name: Configure git to trust the workspace despite the different owner
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Free up disk space
      run: |
        set -x
        # Delete unnecessary files to free up space
        # Workaround to provide additional free space.
        # https://github.com/actions/runner-images/issues/2840
        df -h
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel android-sdk
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          lfs: true
    - name: Build everything
      run: |
        ./scripts/init
        # for some reason with github we must do this
        /opt/toolchains/zephyr-sdk-0.15.1/setup.sh -t all -h -c
        ./scripts/gen-tags cscope
        ./scripts/check
        ./scripts/build-doc --sdk-only
        ./scripts/build
        ./scripts/test
        robot post-build
